### ISSUE TITLE
Add a space between last element of the the list and the next title 

### ISSUE THREAD

**Issue by jordicuevas** [MozillaFoundation/internet-health-report-2018-bugs#10]
### Expected behaviour (How should it be)?
add space between the last item of the list and the title
...

### Actual behaviour (What is wrong)?
difference between title spaces
...

### Steps to reproduce (What should I do to see the problem)?
https://screenshots.firefox.com/I5CbHl4lCoqUR5OO/internethealthreport.org
https://screenshots.firefox.com/Ak2n6LbxWGjNFCyW/internethealthreport.org
...

### Which part of the website does it belong to (add link, if possible)?
https://internethealthreport.org/2018/participa/que-puedes-hacer/?lang=es
https://internethealthreport.org/2018/participate/what-you-can-do/
...

/cc @kaodro

**Comment by kaodro** [comment]
thanks!
