### ISSUE TITLE
space between comments and next articles.

### ISSUE THREAD

**Issue by ghost** [MozillaFoundation/internet-health-report-2018-bugs#11]
### Expected behaviour (How should it be)?
- Instruction "See Mozilla Community Participation Guidelines [English | Español | Deutsch | Français]. Criticize ideas, not people. Offensive comments will be removed. " should be nearer with articles ends. 
- There should not big gaps for comment section, If comment comes, automatically it increase.  There is unnecessary scrolling with current design.

### Actual behaviour (What is wrong)?
A concise way to show data.

### Steps to reproduce (What should I do to see the problem)?
You just need to scroll down in below link.

### Which part of the website does it belong to (add link, if possible)?
[story-of-a-ransomware-victim](https://internethealthreport.org/2018/story-of-a-ransomware-victim/)

/cc @kaodro

**Comment by kaodro** [comment]
This is one of the priorities with styling.

**Comment by dhakelila** [comment]
This was improved some days ago. 
Thanks for flagging! 
![screen shot 2018-04-11 at 11 40 33](https://user-images.githubusercontent.com/6608294/38608995-37b8a84a-3d7d-11e8-980b-09e3f59f6f2b.png)
