### ISSUE TITLE
Spanish version suggestions

### ISSUE THREAD

**Issue by deimidis** [MozillaFoundation/internet-health-report-2018-bugs#13]
### Expected behaviour (How should it be)?

Translation to Spanish. It says: El Informe de la Salud de Internet 2018 es una recopilación de investigación que explica qué está ayudando y qué está afectando a la internet en cinco temas.

Also Download text is still in English, rathern in Spanish: Download Report
...

### Actual behaviour (What is wrong)?

"recopilación" is a group of, so "investigación" in singular seemd odd to me. I think that the best option here is to use plural form for "investigación"

...

### Steps to reproduce (What should I do to see the problem)?

...

### Which part of the website does it belong to (add link, if possible)?

First paragraph on: https://internethealthreport.org/2018/?lang=es
...

/cc @kaodro

**Comment by Solanasaurus** [comment]
Gracias! Let us know if you see anything else.
PDFs for this year (in all the langauages) will be uploaded next week.

**Comment by deimidis** [comment]
I just read two posts and I begun a document to add my comments. Also I made this question to Kasia, what is the best option: create an issue for each *comment/typo* or upload all together in just one document?

**Comment by Solanasaurus** [comment]
Guillermo, thank you!

It might be easiest to put them in a doc if you have found many.

Either that, or just one issue with everything inside.

Thanks very much for the help, super appreciated!

Solana

**Comment by kaodro** [comment]
Changes implemented by Solana.
