### ISSUE TITLE
Styling issues in language switcher in footer

### ISSUE THREAD

**Issue by Solanasaurus** [MozillaFoundation/internet-health-report-2018-bugs#14]
### Expected behaviour (How should it be)?

Aside from being difficult to find, the switcher has a few formatting issues in the text.

### Actual behaviour (What is wrong)?

The text floats out of the box and displays different font sizes.

![image](https://user-images.githubusercontent.com/22150791/38117912-f73aa53a-33b7-11e8-9d9f-44906c0917e0.png)

### Steps to reproduce (What should I do to see the problem)?

Switch languages

### Which part of the website does it belong to (add link, if possible)?

Footer, everywhere.

/cc @kaodro

**Comment by kaodro** [comment]
Also, in Chrome it has another font.
![screen shot 2018-04-04 at 12 32 24 pm](https://user-images.githubusercontent.com/22129061/38302805-47021c24-3804-11e8-9f6d-4f6d9e2f743f.png)
