### ISSUE TITLE
Links on Issue headlines on homepage don't work

### ISSUE THREAD

**Issue by Solanasaurus** [MozillaFoundation/internet-health-report-2018-bugs#15]
### Expected behaviour (How should it be)?

I would expect to be able to click on the big questions on homepage, "Is it safe?", "How open is it?" as well as the tags immediately above them.

### Actual behaviour (What is wrong)?

They are not linked.

### Steps to reproduce (What should I do to see the problem)?

Click on the headlines on homepage.

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018

**Comment by msurman** [comment]
I agree. This is one of the first things I noticed. Important to fix this.

**Comment by kaodro** [comment]
Will be fixed together with the intro linking to "Understand this issue" unfolded on the issue pages.

**Comment by msurman** [comment]
Great. Thank you. Will there be a link to the main section / issue page 
at the end of the intro text that is unfolded?

**Comment by kaodro** [comment]
The intros are on the issue pages so this should solve it!
