### ISSUE TITLE
Sign in button error and typo

### ISSUE THREAD

**Issue by amirad** [MozillaFoundation/internet-health-report-2018-bugs#16]
![screen shot 2018-03-30 at 10 35 41 am](https://user-images.githubusercontent.com/10170768/38141438-2c97e596-3406-11e8-8160-5071a394f20f.png)

### Expected behaviour (How should it be)?
If I want to comment, it asks me to sign in. So I click sign in and the title says "sign in to join the convo or" but there is no or?? Is there supposed to be an or? Or is the or supposed to be deleted?
...

### Actual behaviour (What is wrong)?

...

### Steps to reproduce (What should I do to see the problem)?
Sign in!
...

### Which part of the website does it belong to (add link, if possible)?
I got it in the fake news spotlight page but it probably reproduces elsewhere
...

/cc @kaodro

**Comment by kaodro** [comment]
@Dhakelila need to fix this but maybe we will fix together with Talk's new update?

**Comment by kaodro** [comment]
fixed by Talk
