### ISSUE TITLE
Blog not linked

### ISSUE THREAD

**Issue by amirad** [MozillaFoundation/internet-health-report-2018-bugs#18]
### Expected behaviour (How should it be)?
When you click blog in to the top right corner it should take you to blog: https://internethealthreport.org/blog/
...

### Actual behaviour (What is wrong)?
Instead it takes you to the home page of ihr https://internethealthreport.org/
...

### Steps to reproduce (What should I do to see the problem)?

...

### Which part of the website does it belong to (add link, if possible)?

...

/cc @kaodro

**Comment by kaodro** [comment]
This was actually on purpose as the whole home website is essentially a blog and looks nicer than the /blog but we might change it if it looks like a bug. Thanks!
