### ISSUE TITLE
List of contributors missing from Introduction page

### ISSUE THREAD

**Issue by ldecoursy** [MozillaFoundation/internet-health-report-2018-bugs#19]
### Expected behaviour (How should it be)?

Last line on the page says "See the full list of contributors below."

### Actual behaviour (What is wrong)?

There is nothing listed below.

### Steps to reproduce (What should I do to see the problem)?

Visit link below

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/introduction/

/cc @kaodro

**Comment by kaodro** [comment]
Thanks, Lainie! You can see it once you click on README (https://internethealthreport.org/2018/introduction/readme/) but you definitely spotted a problem here: the README main text shows already when clicking on Introduction and doesn't show the contributors list. We will need to fix this.

**Comment by kaodro** [comment]
@santostiago @Dhakelila
needs a fix - let's show all the README elements text when clicking on Introduction.
