### ISSUE TITLE
Text error "Spotlight: Securing the ‘Internet of Things’ " : They -> The (13th paragraph)

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#21]
### Expected behaviour (How should it be)?

The phrase should be: "**The** key problem is that IoT is …  "

### Actual behaviour (What is wrong)?

The phrase is: "**They** key problem is that IoT is …"

### Steps to reproduce (What should I do to see the problem)?

Read the first phrase of the 13th paragraph of the "Spotlight: Securing the ‘Internet of Things’" article.

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/spotlight-securing-the-internet-of-things/

/cc @kaodro

**Comment by kaodro** [comment]
Thank you! Corrected.
