### ISSUE TITLE
Links to "How healthy is the Internet?" in Introduction are wrong

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#22]
### Expected behaviour (How should it be)?

The links should link to the "How healthy is the Internet?" page of the Introduction section of the website.

### Actual behaviour (What is wrong)?

The links link to the current page.

### Steps to reproduce (What should I do to see the problem)?

Go to Introduction.
Then go to "READ ME" or "2018 Spotlights".
Scroll down until just above the footer (links to other pages of the Introduction section).
Click on the square button with "How is the health of the Internet?".
The actual will just reload instead of going to the "How is the health of the Internet?" page of the Introduction section.

### Which part of the website does it belong to (add link, if possible)?

Links in the "intro-buttons-container" class in the section just above the footer of the following pages:

https://internethealthreport.org/2018/introduction/readme/

and 

https://internethealthreport.org/2018/introduction/spotlights/

/cc @kaodro

**Comment by kaodro** [comment]
@dhakelila the link is correct now but you need to rename it to "How healthy is the Internet?" (now: How is the health of the Internet?"

**Comment by santostiago** [comment]
Fixed :)
