### ISSUE TITLE
Need more space between paragraphs

### ISSUE THREAD

**Issue by deimidis** [MozillaFoundation/internet-health-report-2018-bugs#23]
### Expected behaviour (How should it be)?

Space between paragraphs
...

### Actual behaviour (What is wrong)?
First and second paragraph are separated by only a break of line, qithout extra separation
...

### Steps to reproduce (What should I do to see the problem)?
Look at: [https://internethealthreport.org/2018/una-esperada-mejora-de-internet-esta-en-camino-con-ipv6/](https://internethealthreport.org/2018/an-overdue-internet-upgrade-is-underway-with-ipv6/) and check first and second paragraph
...

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/an-overdue-internet-upgrade-is-underway-with-ipv6/
...

/cc @kaodro

**Comment by kaodro** [comment]
Thanks, corrected. Pls ignore the double graph title, this is on purpose and temporary.
