### ISSUE TITLE
Character limit needs padding next to "post" button for comments

### ISSUE THREAD

**Issue by auremoser** [MozillaFoundation/internet-health-report-2018-bugs#24]
### Expected behaviour (How should it be)?

If a user registers and wants to post a comment on a piece, the character limit should not overlap the "Post" button

### Actual behaviour (What is wrong)?

In Chrome/Firefox, the two overlap and it looks sloppy

### Steps to reproduce (What should I do to see the problem)?

Register for an account to "post comments"
Scroll down on a page to author and post a comment
UI looks sloppy when character limit is hidden by button

### Which part of the website does it belong to (add link, if possible)?

I saw it on every page, but for example here: https://internethealthreport.org/2018/spotlight-securing-the-internet-of-things/

Produces this (full screen, chrome/firefox, 100% resolution): 
![screen shot 2018-03-31 at 4 38 10 pm](https://user-images.githubusercontent.com/1559703/38164313-9d1ad8da-3502-11e8-9f65-1cb5e012c805.png)

/cc @kaodro

**Comment by dhakelila** [comment]
Solved! 

Thanks for spotting! 
![screen shot 2018-04-11 at 11 42 49](https://user-images.githubusercontent.com/6608294/38609109-81492f84-3d7d-11e8-8261-0c7a1a0aeb98.png)

**Comment by kaodro** [comment]
The entire comments section was revamped. Closing!
