### ISSUE TITLE
Sometimes terms are still in english

### ISSUE THREAD

**Issue by deimidis** [MozillaFoundation/internet-health-report-2018-bugs#25]
### Expected behaviour (How should it be)?
You should always read: "Descentralización/Personas" but 
...

### Actual behaviour (What is wrong)?
sometimes you still can read: "Descentralización/People"
...

### Steps to reproduce (What should I do to see the problem)?
Go to link: https://internethealthreport.org/2018/category/descentralizacion/?lang=es and search for Renata's Avila box
...

### Which part of the website does it belong to (add link, if possible)?
Category translation
...

/cc @kaodro

**Comment by kaodro** [comment]
Thanks, Guillermo! I am aware of that. I need to open and close all the posts for it to show the changes - lots of manual work but will get to it this week. Thanks for reporting!

**Comment by kaodro** [comment]
Should be fixed now.
