### ISSUE TITLE
Decentralization blog post - suggestions and changes

### ISSUE THREAD

**Issue by deimidis** [MozillaFoundation/internet-health-report-2018-bugs#26]
Sorry for the long text, but I think that is better to add everything in a single issue, as discussed with @Solanasaurus If it's needed I can divide the text between different issues for each blog post   /cc @kaodro

# Changes to documents

## General
There's a lot of "**–**" that is most used in English than Spanish. In Spanish we use "," or "()" to separate ideas between text.

### ¿Las empresas de tecnología son demasiado grandes? 
https://internethealthreport.org/2018/demasiada-tecnologia/?lang=es

It says:
> “Oigan, empresas, así es como quiero mover mis fotos entre Facebook, Instagram y iPhone”.

Should say:
> “Oigan, empresas, así es como quiero mover mis fotos entre Facebook, Instagram e iPhone”.

### Resistir al colonialismo digital
https://internethealthreport.org/2018/resistir-al-colonialismo-digital/?lang=es

says:
> Antiguamente, los imperios expandieron su poder a través de control de activos claves, desde rutas de comercio hasta océanos, de ferrocarriles a metales preciosos. Ahora, tenemos además los imperios de tecnología que controlan datos y poder computacional para dominar el mundo.

should say:
> Antiguamente, los imperios expandieron su poder a través *del* control de activos claves, desde rutas de comercio hasta océanos, de ferrocarriles a metales preciosos. Ahora, tenemos además los imperios de tecnología que controlan datos y poder computacional para dominar el mundo.

says:
> en Sri Lanka, Bolivia, Eslovaquia, Serbia, Guatemala y Camboya, Facebook introdujo cambios experimentales a las actualizaciones de noticias que instantáneamente corta visitas de páginas de publicaciones y organizaciones a finales de 2017.

should say:
> en Sri Lanka, Bolivia, Eslovaquia, Serbia, Guatemala y Camboya, Facebook introdujo cambios experimentales a las actualizaciones de noticias que instantáneamente redujeron visitas a las páginas de publicaciones y organizaciones a finales de 2017.

says
> Honestamente, no puedo encontrar términos positivos para describir la relación que tenemos hoy con las grandes empresas de tecnología: se basa en la erosión de derechos humanos básicos y extractivismo de datos –y ofrece pocos beneficios a *cambios*. (should be singular: cambio)

says:
> Una versión truncada de internet para los pobres es una dieta de información baja en calorías, una de mera subsistencia y no de desarrollo humano y crecimiento económico. 

And maybe " una mera dieta de subsistencia y no de desarrollo humano" will be better.

says:
> Necesitamos un conocimiento reinventado y datos comunes, y necesitamos innovar formas colaborativas, con financiamiento público de inteligencia artificial por el bien común.

this other option can be more clear:
> Necesitamos un conocimiento reinventado y datos comunes, necesitamos innovar de forma colaborativa, y necesitamos inteligencia artificial con financiamiento público por el bien común.

### El primer embajador del mundo ante el sector tecnológico
https://internethealthreport.org/2018/el-primer-embajador-del-mundo-en-empresas-de-tecnologia/?lang=es

In the picture text there are two typos: *Embajadro* should be *Embajador* and
*technológico* should be *tecnológico*

### Un vigilante ciudadano para la neutralidad de la red en Europa
https://internethealthreport.org/2018/vigilante-ciudadano-para-la-neutralidad-de-la-red-en-europa/?lang=es

1st paragraph says:
> La coalición de defensa SaveTheInternet.euo advierte que no es posible confiar en que los proveedores y los reguladores de internet de la Unión Europea apliquen por sí mismos los principios de la neutralidad en la red.

There's an *o* after the link that has to be deleted

In this paragraph:
> “Si nuestro objetivo es hacer que internet siga siendo libre y abierto, nuestro trabajo no se va a cumplir con mecanismos de defensa que sean teóricos. Debemos ponerlos en práctica en productos del mundo real que infringen la neutralidad en la red”, dice Lohninger.

should said *libre y abierta* internet is a word that use femenine declination.

In the last paragraph:
> Es por eso que, a pesar de saber que probablemente la batalla será difícil, Lohninger aún está optimista sobre el futuro.

I think aún *es* optimista is a better option than *está*

### ¿Un software que necesita personas + (“cadena de bloques”)? 
https://internethealthreport.org/2018/un-software-necesita-personas-blockchain/?lang=es

In this paragraph:
> “La fuente abierta tiene la ventaja económica de dejar que las personas elijan las tareas que consideran importantes, y en las que pueden ser más productivas”, dice Marti, pero insiste en si bien que los incentivos financieros pueden ayudar a hacer sostenible la producción de pares en una economía donde las empresas de emprendimiento se llevan a la mayor parte de los programadores talentosos, el riesgo es que la ayuda voluntaria se apague en el desarrollo de códigos de fuente abierta.

we should change: *...pero insiste en si bien que los incentivos financieros pueden ayudar a hacer sostenible la producción de pares en una economía donde las empresas...* to *pero insiste en que si bien los incentivos financieros pueden ayudar a hacer sostenible la producción de pares en una economía donde las empresas...*

### Construyendo drones submarinos juntos en China
https://internethealthreport.org/2018/construyendo-drones-submarinos-juntos-en-china/?lang=es

It says:
> Chris co-fundó el proyecto Team Tao en 2016. Es una apuesta para ganar los U$7 millones del Shell Ocean Discovery XPRIZE [Premio para el Descubrimiento del Océano de Shell] por medio de la reducción drástica del costo de exploración del fondo del océano. Fui asesor de ese proyecto, y durante el proceso de promoverlo nos dimos cuenta de lo difícil que es que la gente se emocione con el océano.

But Shell and XPRIZE are the comanies behind the prize. So we need to mention both companies or none of them. Maybe enclosing prize with commas:

"Premio para el Descubrimiento del Océano" de Shell y XPRIZE

### Aumenta el apoyo a las protecciones de la neutralidad en la red
https://internethealthreport.org/2018/aumenta-el-apoyo-a-las-protecciones-de-la-neutralidad-en-la-red/?lang=es

Map is not working

## Reactions

Reaction explanations are still in english: Surprised, Thinking, etc

**Comment by Solanasaurus** [comment]
So super thankful for all these corrections, you found some really key ones.
