### ISSUE TITLE
Location of option to switch languages

### ISSUE THREAD

**Issue by arlissc** [MozillaFoundation/internet-health-report-2018-bugs#28]
### Expected behaviour (How should it be)?
I would have expected to be able to switch languages at the top right-hand corner of the landing page so I could immediately know that this is possible ?  the website may be smart to know that I want english based on my browser but if not, I would want to be able to see early that I can switch languages.
...

### Actual behaviour (What is wrong)?
You need to scroll all the way to the bottom to find out that you can change languages
...

### Steps to reproduce (What should I do to see the problem)?
Note:   once you hit the landing page there is no easy way to switch languages before you start reading the site.
...

### Which part of the website does it belong to (add link, if possible)?
landing page, and other pages (I guess, if someone doesn't arrive on the landing page)
...

/cc @kaodro

**Comment by Solanasaurus** [comment]
The website does indeed show you the language version that matches your browser.

We had a discussion about where to put the language switcher at the beginning of the design process with UX logic being that it's repetitive to see it all the time at the top, when you only use it once or never. I'm channeling the winning arguments since I originally also voted for up top :)

**Comment by kaodro** [comment]
I am also annoyed by it being at the bottom and will bring it up again. It is a minor issue though given you change it once only. Let' keep it as a nice-to-have with a higher priority than other nice-to-haves:)

**Comment by kaodro** [comment]
@Dhakelila, can you see if there is an easy way to move the switcher to the top part of the website? If it's easy, let's do it on Friday/Monday once priority items are done.

**Comment by kaodro** [comment]
Fixed! I am sooo happy about the solution.
