### ISSUE TITLE
Report PDF link is odd and links to wrong version

### ISSUE THREAD

**Issue by franziskuskiefer** [MozillaFoundation/internet-health-report-2018-bugs#3]
### Expected behaviour (How should it be)?

* Click Download report.
* Get IHR 2018

### Actual behaviour (What is wrong)?

* Download report is not clickable
![image](https://user-images.githubusercontent.com/890105/38092831-a114ceb8-3369-11e8-9e23-6b16674463cb.png)
* Donloading the full report .pdf gives the 2017 v0.1 report

### Steps to reproduce (What should I do to see the problem)?

* Try to click the link
* Download the pdf

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/

/cc @kaodro

**Comment by Solanasaurus** [comment]
PDF isn't done yet, we'll be adding a link to the real thing as soon as it's ready.
