### ISSUE TITLE
The intro text for each section if really hidden -- no one will find or read this material

### ISSUE THREAD

**Issue by msurman** [MozillaFoundation/internet-health-report-2018-bugs#31]
### Expected behaviour (How should it be)?

When I land at an issue section, I expect to be introduced to the topic -- and invited to read more. We have invested a huge amount of time writing intro sections to help with this. 

### Actual behaviour (What is wrong)?

Right now, you just see the issue heading, the issue tagline and 'learn more'. This gives the reader almost zero understanding that there is valuable content below the 'learn more' and doe does not frame the page with the Mozilla point of view on the issue (the point of those intros).

### Suggestions

We need to find a way to drive more users to those intro pages and integrate them more into the experience. 

A simple hack would be to a) add the first paragraph of the body copy into the current pages and then b) replace 'learn more' with 'Read privacy and security primer' (or something like that).

We could also embed links to the intros directly to the intro pages within the issue blocks on the home page. E.g. 'Get an overview of privacy and security issues'.

Whatever we choose to do, we need to drive more people to this intro content.

...

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/category/privacy-and-security/
and the other four issue pages

/cc @kaodro

**Comment by kaodro** [comment]
Thanks, Mark! I agree, they are pretty hidden and there is not much incentive to open the "Learn More", it was my concern, too. 

@solanasaurus How about changing the prompt to "Understand the issue" or "What is the problem?" ( a bit more provocative?) or what Mark suggested? Ideas?
Showing the first paragraph would be an option but I would need Vizzuality to re-code that as the field doesn't allow so many characters right now. Will ask unless you have a better idea?
Lastly, an additional idea would be to link the headlines on the homepage and make them open to an unfolded intro text on the issue page (we have a [ticket for linking these headlines already](https://github.com/MozillaFoundation/internet-health-report-2018-bugs/issues/15)). 
I would vote for doing all of these things.

**Comment by kaodro** [comment]
We will start with 
a) Changing the prompt "Learn more" into "Understand this issue" or "Your guide to this issue"
b) Linking the headlines on the homepage to an unfolded text

**Comment by kaodro** [comment]
We have much more prominent buttons renamed into "Understand this issue" and links from the homepage to the Intros. Closing.

**Comment by msurman** [comment]
The "Understand this issue" text on issue pages is great.
However, I don't see links from the homepage to the Intros. The homepage just links to the main issue pages.
Did we decide not to implement the link from the homepage to the intros?

**Comment by Solanasaurus** [comment]
There was no way to link to the pages with the text unfolded, and we worried about pushing down the “buffet” of other stories if we simply to have the text unfolded all the time. Only reasonable alternative would have been to make the intros their own article and pin them to the top, but it seemed better to give them this special position above the other stories.

Sorry!
