### ISSUE TITLE
The overall intro needs better way to drive traffic

### ISSUE THREAD

**Issue by msurman** [MozillaFoundation/internet-health-report-2018-bugs#32]
### Expected behaviour (How should it be)?

I should be invited into the report to get context when I first land at the site. It's important that people are guided to the read me and intro if they are wondering 'what is this thing?'

### Actual behaviour (What is wrong)?

The only way I get context is to notice the intro and readme in 'about' -- which is not really where I'd normally go and most users won't take the time to look here.

### Suggestion

Integrate some sort of push to the  'readme' within the scroll of the first page. Maybe a 'Read intro' and 'Why is this report?'' as text links beside the PDF download.

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/

/cc @kaodro

**Comment by kaodro** [comment]
We will add a link, great hint!

**Comment by clementprdhomme** [comment]
Hey Kasia, we've added a new link:
<img width="1290" alt="A new link 'Why this report?' is shown in the introduction, on the homepage" src="https://user-images.githubusercontent.com/6073968/38417449-3dc0ea22-3990-11e8-9988-9e305c068822.png">

Hope that will do!

**Comment by kaodro** [comment]
Thanks, very cool. Could you rename it to README? And link the big tag "How healthy is the Internet" to the How healthy is the Internet? (just like you did with the tags for the issues) thanks @clementprdhomme
