### ISSUE TITLE
Changes proposed for "Mejorando la seguridad de la 'internet de las cosas'

### ISSUE THREAD

**Issue by deimidis** [MozillaFoundation/internet-health-report-2018-bugs#33]
### Expected behaviour (How should it be)?
Another file with changes for spanish translation of a blog post
...

### Actual behaviour (What is wrong)?
There are some changes needed for more clarity
...

### Steps to reproduce (What should I do to see the problem)?

...

## Mejorando la seguridad de la ‘Internet de las Cosas’
https://internethealthreport.org/2018/destacado-mejorando-la-seguridad-de-la-internet-de-las-cosas/?lang=es

Says

> En algún lugar de Vietnam, un hombre busca una caja de zapatos en un almacén, una mujer corta una rodaja de pan en Argentina y un niño se sienta inquieto en el regazo de su madre en la sala de espera de lo que parece ser una farmacia en Francia. En Alemania, alguien ordeña una vaca.

Clearer way:

>En algún lugar de Vietnam, un hombre busca una caja de zapatos en un almacén; una mujer corta una rodaja de pan en Argentina; un niño se sienta inquieto en el regazo de su madre en la sala de espera de lo que parece ser una farmacia en Francia y en Alemania, alguien ordeña una vaca.

It says:
>Seguramente, ellos no saben que los puede ver cualquier persona que busque cámaras inseguras en internet.

Another option:
> Seguramente ellos no saben que los puede ver cualquier persona que busque cámaras inseguras en internet.

It says:

>Cuando configuramos una cámara podríamos elegir restringir el acceso ella estableciendo una contraseña.

Should say:
> Cuando configuramos una cámara podríamos elegir restringir el acceso **_a_** ella estableciendo una contraseña.

It says:
> Son 30 mil millones de dispositivos en todo el mundo. Por cada dispositivo que no tiene contraseña o que cuenta con una contraseña débil, internet se vuelve un poco más frágil y peligrosa.

be better:
> **Serán** 30 mil millones de dispositivos en todo el mundo. **Con** cada dispositivo que no tiene contraseña o que cuenta con una contraseña débil, internet se vuelve un poco más frágil y peligrosa.

take out this sign:

> Se recopilará información que es vulnerable a ataques y a filtraciones. Podríamos preocuparnos por degenerados que buscan personas desnudas~~,~~ que no sospechan su presencia o por quienes pudiesen realizar fraudes financieros o publicidad invasiva o manipulación política.

It says:
>En diciembre de 2017, tres jóvenes se declararon culpables en una corte federal estadounidense de haber creado una cadena de software malicioso llamado Mirai en 2016 que esclavizó a miles y miles de cámaras web, monitores de bebé y otros dispositivos que venían con nombres de usuario y contraseñas definidos por defecto desde la fábrica que llevaron a cabo “ataques DDoS” para cerrar sitios web y redes. 

Clearer way:
> En diciembre de 2017, en una corte federal estadounidense, tres jóvenes se declararon culpables de haber creado, en 2016, una pieza de software malicioso llamado Mirai que esclavizó a miles y miles de cámaras web, monitores de bebé y otros dispositivos que aún usaban los nombres de usuario y contraseñas definidos por defecto desde la fábrica. Con ellas llevaron a cabo “ataques DDoS” para cerrar sitios web y redes. 

Says:
> El problema clave es que la IoT está creciendo más rápido y más de lo que hubiéremos podido imaginar. 

change: *hubiéremos* to *hubiéramos* 
...

/cc @kaodro

**Comment by kaodro** [comment]
Thanks so much, Guillermo! We will implement the changes.

**Comment by kaodro** [comment]
Implemented by @Solanasaurus for the most part. Thanks!
