### ISSUE TITLE
Space between article and comments

### ISSUE THREAD

**Issue by Solanasaurus** [MozillaFoundation/internet-health-report-2018-bugs#35]
### Expected behaviour (How should it be)?

I think this is already being worked on but there is a lot of empty space between the end of the article and comments that doesn't seem like it should be there.

### Actual behaviour (What is wrong)?

Too much empty space (viewing in Firefox)

### Steps to reproduce (What should I do to see the problem)?

![image](https://user-images.githubusercontent.com/22150791/38251645-56eeae20-3752-11e8-94fd-f2b8157e5cb8.png)

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/meet-the-internets-first-responders-to-security-emergencies/

/cc @kaodro

**Comment by kaodro** [comment]
Clara, is this being fixed with styling?

**Comment by dhakelila** [comment]
Yes, this was address.
Thanks :)
![screen shot 2018-04-11 at 11 46 08](https://user-images.githubusercontent.com/6608294/38609280-f3090acc-3d7d-11e8-9523-738712674279.png)
