### ISSUE TITLE
404 / URL-unknown page needs styling

### ISSUE THREAD

**Issue by Solanasaurus** [MozillaFoundation/internet-health-report-2018-bugs#38]
### Expected behaviour (How should it be)?

404 page that says something like "Page not found".

### Actual behaviour (What is wrong)?

The page is there, it just has too many elements and needs styling. We could remove everything except the headline that says "Oops. Page not found". Not sure if that string is translatable.

### Steps to reproduce (What should I do to see the problem)?

![image](https://user-images.githubusercontent.com/22150791/38279113-22a309ac-379f-11e8-80b6-6c2b816ff416.png)

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/x

/cc @kaodro

**Comment by dhakelila** [comment]
Updated! :)
![screen shot 2018-04-11 at 11 47 12](https://user-images.githubusercontent.com/6608294/38609342-18d5ca42-3d7e-11e8-8dc6-b178e992eb98.png)
