### ISSUE TITLE
README says "Download the abridged PDF, or explore online" and I expected those to be links

### ISSUE THREAD

**Issue by chutten** [MozillaFoundation/internet-health-report-2018-bugs#4]
### Expected behaviour (How should it be)?
On https://internethealthreport.org/2018/introduction/readme/ above the Credits I found the phrase "Download the abridged PDF, or explore online."

I expected "abridged PDF" and "explore online" to be links.
...

### Actual behaviour (What is wrong)?
No links
...

### Steps to reproduce (What should I do to see the problem)?
Load https://internethealthreport.org/2018/introduction/readme/
...

### Which part of the website does it belong to (add link, if possible)?
https://internethealthreport.org/2018/introduction/readme/
...

/cc @kaodro

---

This could very well be intentional.

**Comment by Solanasaurus** [comment]
The PDF is not done yet, we'll make sure to add a link - thanks for flagging.

**Comment by kaodro** [comment]
the link to the PDF has been added!
