### ISSUE TITLE
Test color blog

### ISSUE THREAD

**Issue by ghost** [MozillaFoundation/internet-health-report-2018-bugs#40]
### Expected behaviour (How should it be)?
There should not be blog named as "test color" with no content. Seems like ["Who controls it"](https://internethealthreport.org/2018/who-controls-it/) blog is still under process.

### Actual behaviour (What is wrong)?
I don't know it is intentionally created for testing but should be removed before realse. 

### Steps to reproduce (What should I do to see the problem)?
1. Go to Search
2. Select decentralization issue with type people.

### Which part of the website does it belong to (add link, if possible)?
[here](https://internethealthreport.org/2018/?issue=Decentralization&type=People&s=)

/cc @kaodro

**Comment by kaodro** [comment]
Thanks! I trashed these posts, thank you for spotting.
