### ISSUE TITLE
Article title is weird - Software needs people + (“Blockchain”)?; 

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/internet-health-report-2018-bugs#42]
### Expected behaviour (How should it be)?
Title should read: Software needs people + “Blockchain”?
... or something else?

### Actual behaviour (What is wrong)?
Title reads: Software needs people + (“Blockchain”)?; 
Punctuation looks weird 

### Steps to reproduce (What should I do to see the problem)?
https://internethealthreport.org/2018/software-needs-people-blockchain/

### Which part of the website does it belong to (add link, if possible)?https://internethealthreport.org/2018/software-needs-people-blockchain/

/cc @kaodro

**Comment by kaodro** [comment]
This is actually intended :) It is "code" language approved by a programmer

**Comment by samanthaburton** [comment]
Hah! Awesome. Clearly I'm not the intended audience... ;)
