### ISSUE TITLE
Formatting for FR and DE 'Participate' pages

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/internet-health-report-2018-bugs#43]
### Expected behaviour (How should it be)?
Styling should be the same as the EN Participate page
...

### Actual behaviour (What is wrong)?
FR Participate page -- no headings, inconsistent spacing
DE Participate page -- inconsistent spacing
...

### Steps to reproduce (What should I do to see the problem)?
Go to Participate page, and switch to the different languages
...

### Which part of the website does it belong to (add link, if possible)?
https://internethealthreport.org/2018/participate/what-you-can-do/?lang=fr
https://internethealthreport.org/2018/participate/what-you-can-do/?lang=de
...

/cc @kaodro

**Comment by kaodro** [comment]
I fixed it and added liked orgs to all lang.
