### ISSUE TITLE
Is it possible to have the Language drop-down menu in the header?

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/internet-health-report-2018-bugs#44]
### Expected behaviour (How should it be)?
Language drop-down should be easy to find (eg in header of pages)
...

### Actual behaviour (What is wrong)?
It's currently in the footer, and it's hard to find there
...

### Steps to reproduce (What should I do to see the problem)?
Look in any footer!
...

### Which part of the website does it belong to (add link, if possible)?
...

/cc @kaodro

**Comment by kaodro** [comment]
Fixed in a very cool way!
