### ISSUE TITLE
Participate card has incorrect header in Search

### ISSUE THREAD

**Issue by samanthaburton** [MozillaFoundation/internet-health-report-2018-bugs#45]
### Expected behaviour (How should it be)?
Participate card should be labeled 'participate'
...

### Actual behaviour (What is wrong)?
It's labeled Normal: Normal
...

### Steps to reproduce (What should I do to see the problem)?
https://internethealthreport.org/2018/?issue=&type=&s=participate
...

### Which part of the website does it belong to (add link, if possible)?
...

/cc @kaodro

**Comment by samanthaburton** [comment]
This may actually be true for any card that links to a page that isn't an article or data: see the same thing for Issues card - https://internethealthreport.org/2018/?issue=&type=&s=issues

**Comment by kaodro** [comment]
Pages were not supposed to show up in search results, Vizz is removing them now. Thanks for spotting!
