### ISSUE TITLE
The emphasis on "and" reads a little strangely

### ISSUE THREAD

**Issue by chutten** [MozillaFoundation/internet-health-report-2018-bugs#5]
### Expected behaviour (How should it be)?
In https://internethealthreport.org/2018/introduction/how-healthy-is-the-internet/ there is a sentence "In Too big tech? we explore how the dominant companies of the United States and China create unhealthy conditions for struggling innovators and smaller populations trying to break into the market – and for a scientist trying to untangle himself from Google." which as an emphasis on the word "and" between "United States" and "China"

To me that seems editorial and distracting.
...

### Actual behaviour (What is wrong)?

...

### Steps to reproduce (What should I do to see the problem)?

...

### Which part of the website does it belong to (add link, if possible)?

...

/cc @kaodro

---
This bug report's an opinion. It's probably nothing, but I felt I should share it.

**Comment by kaodro** [comment]
fixed, thanks!
