### ISSUE TITLE
height in graph too short to display numbers properly

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#50]
### Expected behaviour (How should it be)?

The numbers on top of the histogram should be displayed properly.

### Actual behaviour (What is wrong)?

The number for Smartphone is not readable, is cut off on medium to large screens. It looks ok on mobile.

### Steps to reproduce (What should I do to see the problem)?

On a laptop, desktop computer or tablet, go to the _**“Ultra nerds” are more optimistic about our connected future**_ article in "Privacy and security"

Go to the graph below Types of devices people own and observe the number for Smartphone

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/ultra-nerds-are-more-optimistic-about-our-connected-future/
Graph below Types of devices people own

/cc @kaodro

**Comment by clementprdhomme** [comment]
Hi Cecile!

Thank you for filing the issue. We've just adjusted the bar chart so the values above the rectangles are not cut anymore.

Please empty the cache of your browser otherwise you might still see the bug.

Clément
