### ISSUE TITLE
French version, space missing in text « coalition du rapport»

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#51]
### Expected behaviour (How should it be)?

« coalition du rapport »

### Actual behaviour (What is wrong)?

« coalition du rapport»

### Steps to reproduce (What should I do to see the problem)?

Go to README of the Introduction in the **french** version.
Go to the 9th paragraph

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/introduction/readme/?lang=fr

9th paragraph

/cc @kaodro

**Comment by kaodro** [comment]
fixed!
