### ISSUE TITLE
French version: space missing "Comment se porte Internet?" button

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#52]
### Expected behaviour (How should it be)?

Comment se porte Internet ?

### Actual behaviour (What is wrong)?

Comment se porte Internet?

Non-breaking space missing before ?

### Steps to reproduce (What should I do to see the problem)?

In the french version, go to Introduction and choose README or Enjeux 2018.
Scroll down to the just above the footer.
Observe the button "Comment se porte Internet?"

### Which part of the website does it belong to (add link, if possible)?

https://internethealthreport.org/2018/introduction/2018-spotlights/?lang=fr
https://internethealthreport.org/2018/introduction/readme/?lang=fr

/cc @kaodro

**Comment by cecilebertin** [comment]
Space also missing before question marks in footer of the french version website.

**_Comment se porte Internet?
Comment agir?_**

**Comment by kaodro** [comment]
fixed!
