### ISSUE TITLE
double punctuation in footer in french version

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#53]
### Expected behaviour (How should it be)?

J’accepte que Mozilla traite mes informations conformément à sa politique de confidentialité.

### Actual behaviour (What is wrong)?

J’accepte que Mozilla traite mes informations conformément à sa politique de confidentialité. . 

### Steps to reproduce (What should I do to see the problem)?

In the french version, go to the footer.
Observe the text just below the subscribe button.

### Which part of the website does it belong to (add link, if possible)?

Footer of the whole french version website.

/cc @kaodro

**Comment by kaodro** [comment]
thanks! fixed
