### ISSUE TITLE
Share on Twitter icon does not appear in Safari

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#56]
### Expected behaviour (How should it be)?

Twitter icon should appear next to Facebook icon

<img width="404" alt="capture d ecran 2018-04-09 a 12 39 28" src="https://user-images.githubusercontent.com/21285660/38518980-4b86c1d0-3bf3-11e8-802b-ed1ac1178eb8.png">

### Actual behaviour (What is wrong)?

Only the Facebook icon is shown
<img width="398" alt="capture d ecran 2018-04-09 a 12 39 03" src="https://user-images.githubusercontent.com/21285660/38519012-579cebc0-3bf3-11e8-8685-041e3d996a08.png">

### Steps to reproduce (What should I do to see the problem)?

1. Open an article from an Issue in Safari.
2. Scroll down to the bottom of the article (just before the comment section)
3. Observe the feelings (emojis) section and fixed bar at the bottom of the page.

### Which part of the website does it belong to (add link, if possible)?

/cc @kaodro

**Comment by kaodro** [comment]
I can see it, have you tried clearing the cache? The site caches a lot so you might be still on some version before changes?

**Comment by cecilebertin** [comment]
You're right, it works
