### ISSUE TITLE
Comment section buttons appearance

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#57]
### Expected behaviour (How should it be)?

The buttons should look the same on all browsers.
The size and location of the buttons should not change when clicking or hovering on them. (no shifting)

### Actual behaviour (What is wrong)?

The buttons look different in Safari.
Safari: <img width="406" alt="capture d ecran 2018-04-09 a 12 56 31" src="https://user-images.githubusercontent.com/21285660/38519689-84f63c96-3bf5-11e8-8793-4f45a0cb6d66.png">

Firefox & Chrome: <img width="422" alt="capture d ecran 2018-04-09 a 12 56 25" src="https://user-images.githubusercontent.com/21285660/38519704-916ee9f0-3bf5-11e8-8e23-963febf1f333.png">

There is a shifting and change in size in Firefox only, when hovering on the buttons.
![capture d ecran 2018-04-09 a 13 00 24](https://user-images.githubusercontent.com/21285660/38520833-c78b4d00-3bf8-11e8-96c5-51c50c40c20c.gif)

There is a shifting and change in size in the buttons when clicking on Comments when in My Profile and vice versa.
![capture d ecran 2018-04-09 a 13 23 56](https://user-images.githubusercontent.com/21285660/38521561-ebb22792-3bfa-11e8-930d-30e0736024a1.gif)

### Steps to reproduce (What should I do to see the problem)?

1. Go to the comment section of an article for an issue.
2. Hover or click on the Comments and My Profile buttons.

### Which part of the website does it belong to (add link, if possible)?

Comments section of each article in an issue.

/cc @kaodro

**Comment by dhakelila** [comment]
Fixed now! Thank you for checking!

**Comment by cecilebertin** [comment]
Hi @dhakelila,

 I don't see any changes in Safari.

**Comment by cecilebertin** [comment]
Also, those buttons in **Safari for iOS** and in **Firefox for iOS** look the same as they look in Safari for desktop.
<img width="320" alt="image-1" src="https://user-images.githubusercontent.com/21285660/38647406-f5f452fa-3da0-11e8-8856-008de03cdc1d.png">
