### ISSUE TITLE
Missing "and" in list of items

### ISSUE THREAD

**Issue by chutten** [MozillaFoundation/internet-health-report-2018-bugs#6]
### Expected behaviour (How should it be)?
I expect an 'and' in the list " access, affordability, encryption"
...

### Actual behaviour (What is wrong)?

...

### Steps to reproduce (What should I do to see the problem)?
In https://internethealthreport.org/2018/introduction/how-healthy-is-the-internet/ there is a sentence  "Things are getting a bit better in areas like: access, affordability, encryption."
...

### Which part of the website does it belong to (add link, if possible)?

...

/cc @kaodro
---
Might be intentional, given the next sentence begins with And. I'm not a writer, just an amateur proofreader.

**Comment by Solanasaurus** [comment]
It's better with "and" thank you (added on website)
