### ISSUE TITLE
Footer sign up form broken at small widths

### ISSUE THREAD

**Issue by cadecairos** [MozillaFoundation/internet-health-report-2018-bugs#67]
### Expected behaviour (How should it be)?

at small widths, the signup form should display properly and be usable

### Actual behaviour (What is wrong)?

At small screen widths, the sign up form doesn't display correctly in non-blink/webkit browsers (tested in Firefox and Edge)

### Steps to reproduce (What should I do to see the problem)?

On Firefox, you can toggle "Responsive Design View" with `Ctrl+Shift+M` (Command if on Mac) and change the size of the screen

![2018-04-10_09-28-44](https://user-images.githubusercontent.com/438003/38559667-a3318e7a-3ca1-11e8-9ae4-df54f911175b.gif)

### Which part of the website does it belong to (add link, if possible)?

Any page on `/2018` with a footer

/cc @kaodro

**Comment by kaodro** [comment]
@dahakelila here is something to fix tomorrow

**Comment by clementprdhomme** [comment]
Hi Christopher,

Thanks for filing the issue!

We've just fixed the bug and it's now looking good 😀. Don't forget to empty your cache to make sure you still don't see this little 🐛.
