### ISSUE TITLE
article post titles not responsive in mobile

### ISSUE THREAD

**Issue by jordicuevas** [MozillaFoundation/internet-health-report-2018-bugs#69]
### Expected behaviour (How should it be)?
article titles should fit the parent container
...

### Actual behaviour (What is wrong)?
article titles not fitting parent container in mobile version
https://screenshots.firefox.com/9tlIsMhuXwj9m6m1/mobiletest.me
...

### Steps to reproduce (What should I do to see the problem)?
open this article in a mobile phone ex. Iphone5 or crtl +shift + m
https://internethealthreport.org/2018/software-needs-people-blockchain/
https://screenshots.firefox.com/9tlIsMhuXwj9m6m1/mobiletest.me
...

### Which part of the website does it belong to (add link, if possible)?
articles with long post titles
...
### possible fix
add a media query with a smaller font size for mobile phones 

/cc @kaodro

**Comment by clementprdhomme** [comment]
Hi Jord,

Thanks for reporting this. We're progressively enhancing the mobile experience and as part of today's deployment, we've made the following changes:
- smaller font sizes across the project (on mobile)
- smaller side margins for the posts (on mobile)

<div align="center">

![Smaller margins and font sizes on the posts](https://user-images.githubusercontent.com/6073968/38615840-fe01115c-3d89-11e8-8d79-7e8be2bbc5db.png)
</div>

Other areas of the report will be updated in the coming days.

@kaodro I think the issue can be closed.

Clément

**Comment by kaodro** [comment]
thanks for fixing
