### ISSUE TITLE
2018 Spotlights has no spotlights

### ISSUE THREAD

**Issue by chutten** [MozillaFoundation/internet-health-report-2018-bugs#7]
### Expected behaviour (How should it be)?
Clicked on "2018 Spotlights" in the introduction header available on "How healthy is the Internet?". The resulting page had one paragraph of prose, and that was it.

I expected to see spot-lit problems and solutions.
...

### Actual behaviour (What is wrong)?

...

### Steps to reproduce (What should I do to see the problem)?
Load https://internethealthreport.org/2018/introduction/how-healthy-is-the-internet/
Click on "2018 spotlights" in the tab header
...

### Which part of the website does it belong to (add link, if possible)?
https://internethealthreport.org/2018/introduction/spotlights/
...

/cc @kaodro

**Comment by chutten** [comment]
Huh, apparently this works now.

I was just about to file a similar issue for "https://internethealthreport.org/2018/issues/" but then it started working. And now so does spotlights.

Intermittent issue? There were no errors in the developer console (just a log from jquery migrate).

**Comment by Solanasaurus** [comment]
Thank so much! A lot of little changes are happening right now on the website, here and there. I'm reordering the posts on the issue pages, among other things :)
