### ISSUE TITLE
feedback page broken in spanish version

### ISSUE THREAD

**Issue by jordicuevas** [MozillaFoundation/internet-health-report-2018-bugs#70]
### Expected behaviour (How should it be)?
display information about the feedback  page 
...

### Actual behaviour (What is wrong)?
displays a XML error 
https://screenshots.firefox.com/DJo3h5KFHRksM1FT/internethealthreport.org
...

### Steps to reproduce (What should I do to see the problem)?
go to https://internethealthreport.org/es/feedback/
...

### Which part of the website does it belong to (add link, if possible)?
Feedback
...

/cc @kaodro

**Comment by kaodro** [comment]
Thanks! I remove the feedback tab from the blog page - it wasn't working for a while (it was a Coral iframe), thanks for spotting!
