### ISSUE TITLE
Missing title tag on internethealthreport.org/2018

### ISSUE THREAD

**Issue by badboy** [MozillaFoundation/internet-health-report-2018-bugs#71]
### Expected behaviour (How should it be)?

<https://internethealthreport.org/2018/> should have a proper title tag, just as the main site.

### Actual behaviour (What is wrong)?

The title tag on <https://internethealthreport.org/2018/> is empty:

```html
<title></title>
```

/cc @kaodro

**Comment by cecilebertin** [comment]
Same issue as #66

**Comment by badboy** [comment]
Indeed. Closing in favor of #66
