### ISSUE TITLE
Collapse of the commentAuthorTags into the username

### ISSUE THREAD

**Issue by cecilebertin** [MozillaFoundation/internet-health-report-2018-bugs#72]
### Expected behaviour (How should it be)?

<img width="144" alt="capture d ecran 2018-04-11 a 11 57 28" src="https://user-images.githubusercontent.com/21285660/38637297-946d9bf2-3d7f-11e8-9f1b-ebab0054d6dc.png">

### Actual behaviour (What is wrong)?

<img width="144" alt="capture d ecran 2018-04-11 a 11 52 58" src="https://user-images.githubusercontent.com/21285660/38637264-7b80eb6c-3d7f-11e8-8149-a55d3c8bff6b.png"> <img width="144" alt="capture d ecran 2018-04-11 a 11 52 46" src="https://user-images.githubusercontent.com/21285660/38637263-7b622be6-3d7f-11e8-9327-e3b38d28d1f4.png">

### Steps to reproduce (What should I do to see the problem)?

Not sure how to reproduce. It doesn't seem to happen all the time

### Which part of the website does it belong to (add link, if possible)?

Comment section

Some pages where the issue occurs:
https://internethealthreport.org/2018/spotlight-understanding-fake-news/
https://internethealthreport.org/2018/the-top-50-passwords-could-easily-be-better/

/cc @kaodro

**Comment by cecilebertin** [comment]
@losowsky This is maybe a bug from the Talk plugin

**Comment by losowsky** [comment]
Thanks Cecile. These triangles are something you added in your designs, I think? I've never seen them in Talk before, so it might be an issue with the CSS you added? @cecilebertin

**Comment by cecilebertin** [comment]
Oh ok sorry, thanks! I didn't know the CSS for the plugin was not done by you. It makes sense.

**Comment by kaodro** [comment]
I know about that, my own name was displaying like this in the feedback page. This is fixed now, you need to clear your cache. But let me know if you still see it.

**Comment by cecilebertin** [comment]
Your right, it's fixed. I should clear my cache and check the issue before reporting a bug.

**Comment by kaodro** [comment]
No worries, happens to me all-the-time.
